### ISSUE TITLE
TypeError: Cannot read property 'worksheets' of undefined

### ISSUE THREAD

**Issue by dsdannynikravesh** [brandonmp/gatsby-source-google-sheets#45]
Hi all! I know this Error is highlighted at the bottom of the `README` under Troubleshooting. 

- _If you get the error "Cannot read property 'worksheets' of undefined", make sure you have shared your spreadsheet with your service account user._

Followed the troubleshooting suggestions and I am still left with the error.

I weirdly received this error yesterday, and made sure that the service account user had been shared with the spreadsheet. Creating a new service account however seemed to temporary fix the issue until now.

Getting the same error and creating a new service account is not able to fix the issue this time.

Let me know if theres any further information I can provide! Any help is much appreciated! Thank you!

**Comment by rajan-magar** [comment]
Same issue on this side.
FYI @brandonmp @MartinNuc @drewatk @KyleAMathews @britt @j-nolan

**Comment by div-cowboy** [comment]
Same issue

**Comment by advisciglio** [comment]
This seems to be related to https://github.com/brandonmp/gatsby-source-google-sheets/issues/39, caused by the Google API V3 version being recently deprecated.

Provided this plugin doesn't seem to be supported anymore, I suggest replacing it with https://github.com/sondrele/gatsby-source-google-spreadsheet. I could replace it successfully in my project; there are minor implementation differences but overall it's pretty much the same.

Some differences I stumbled upon:
- The new plugin retrieves all sheets with one configuration object (as opposed to one object per sheet)
- The new plugin returns boolean values (checkboxes) as `TRUE` or `FALSE` strings
- The graphql node types have a different type (`allGoogleSheetSheetnameRow` vs. `allGoogleSpreadsheetSheetname`)

**Comment by rajan-magar** [comment]
@advisciglio Agree. It seems they dropped it on 2nd August, 2021 and its weird we are facing this issue since 16 August, 2021. Anyway, i have gone through the migration part and noticed the changed the URL's for API which we might need to implement here in this project. So we can use the same plugin instead of going to another plugin. 
FYI @brandonmp @MartinNuc @drewatk @KyleAMathews @britt @j-nolan

**Comment by ehannes** [comment]
@rajan-magar are you working with a migration? Would be great to be able to continue using this plugin, we use it in several projects.

I also opened #46 to see if we can get in touch with the author of this plugin since it seems abandoned. Otherwise, we might need to fork it... Maybe start a community around it?

I will also take a deeper look at the suggested alternative above, though latest update there is also old: Oct 30, 2019...

**Comment by ehannes** [comment]
Looks like @yeswanth has a working version here: https://github.com/yeswanth/gatsby-source-google-sheets.
Also looks like @advisciglio has one here: https://github.com/advisciglio/gatsby-source-google-sheets

Any chance we can create a GitHub organisation and work together on a successor of this plugin instead of building our own versions? :smile:

**Comment by advisciglio** [comment]
@ehannes I ended up using https://github.com/sondrele/gatsby-source-google-spreadsheet to fix the Google API issue. The repo you reference is a fork from the original that I had to make in order to bridge the Gatsby v2 to v3 issue, but I think it still has permission failures (I stopped using it altogether).

**Comment by yeswanth** [comment]
@ehannes Definitely a good idea. I would love to collaborate with you on this.

**Comment by ehannes** [comment]
@yeswanth are your version of the plugin working? If so, then maybe we could continue with either:
- Create an organisation here on Github so that we co-own the project
- Or invite me and hopefully other collaborators to your repository
- Or at least open it up your repository so that one can submit issues

Would also be nice if we could release the plugin officially at npmjs.org.

Maybe you could contact me at hannes@accodeing.com to discuss the details further? Thanks for wanting to share :smile:

**Comment by ehannes** [comment]
@advisciglio good that you found a solution. Is that other plugin maintained? It has just 15 commits and last one was made Oct 30, 2019. Does it support Gatsby v3?

**Comment by advisciglio** [comment]
@ehannes I am using it with V2 but I think it should work on V3 as well.

In `gatsby-source-google-sheets`, the v3 incompatibility relies on the usage of `boundActionCreators`, which was deprecated in favor of `actions` (see https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/#removal-of-boundactioncreators).

`gatsby-source-google-spreadsheet` uses `actions`, for which I _assume_ it should work with Gatsby v3.

In regards to plugin maintenance, yes, it looks less popular and equally abandoned.

**Comment by ehannes** [comment]
@yeswanth any change we can get in contact? :smiley:

**Comment by yeswanth** [comment]
@advisciglio Yes, I just sent you a mail :)

**Comment by ehannes** [comment]
Unfortunately, this repository seems completely abandoned, and as this issue describes, it's also broken. @yeswanth and I have decided to use his working fork of the project and continue maintenance there. So, if anyone is interested, you can find it here: https://github.com/yeswanth/gatsby-source-google-sheets.

**Comment by dsdannynikravesh** [comment]
As per @ehannes message above I am closing this as it is apparent that this plugin is no longer functional with Google updating their API and this plugin not being maintained. 

Ive decided to move the google sheets into a `csv` folder within the repository and use [gatsby-transormer-csv](https://www.gatsbyjs.com/plugins/gatsby-transformer-csv/) as a quick solution.

For anyone wanting a google-sheets plugin see @ehannes' link above.
